{% set name = "mplsignal" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mplsignal-{{ version }}.tar.gz
  sha256: 05f337dc4d6dd5f711ecfcdc3971304461fb54750c7c1ebd4f771d88064744f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - matplotlib-base
    - adjusttext

test:
  imports:
    - mplsignal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/oscargus/mplsignal
  summary: Matplotlib extension for signal processing-related plots
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://mplsignal.readthedocs.io/
  dev_url: https://github.com/oscargus/mplsignal

extra:
  recipe-maintainers:
    - oscargus
